# Documentation: https://roots.io/trellis/docs/local-development-setup/
wordpress_sites:
  babat.fr:
    site_hosts:
      - babat.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    site_install: false
    site_title: babat Site
    admin_user: admin
    # admin_password: (defined in group_vars/development/vault.yml)
    admin_email: admin@babat.dev
    initial_permalink_structure: /%postname%/ # applied only at time of WP install and when `site_install: true`
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: http://babat.dev
      wp_siteurl: http://babat.dev/wp
      wp_env: development
      db_name: babat_dev
      db_user: babat_dbuser
      # db_password: (defined in group_vars/development/vault.yml)
